//
// Created by Bohlender,Ryan James on 8/4/18.
//

#include <stocc/stocc.h>
#include <ctime>
#include <thread>
#include <cassert>
#include <fmt/include/fmt/ostream.h>
#include "permutation.hpp"

/**
 * @brief Default construction of the Permute object.
 *
 * Always has a random seed, generated by std::random_device.
 */
Permute::Permute()
	: sto(std::random_device{}()) {}

/**
 * @brief Constructor for the Permute object with a known seed.
 * @param seed The random seed.
 */
Permute::Permute(int seed)
	: sto(seed) {}

void Permute::get_permutations(const std::shared_ptr<std::vector<std::vector<int32_t>>> &permutations,
							   arma::vec &odds,
							   int ncases,
							   int nperm,
							   int nthreads) {
  std::vector<double> odds_ = arma::conv_to<std::vector<double>>::from(odds);
  std::vector<int32_t> m(odds.n_rows, 1);

  // Initialize permutations
  permutations->resize(nperm);
  for (int i = 0; i < nperm; i++) {
	(*permutations)[i].resize(odds.n_rows);
  }

  int step = nperm / nthreads;
  int remaining = nperm;
  std::vector<std::thread> threads;
  for (int i = 0; i < nthreads; i++) {
	int seed = sto.IRandom(0, std::numeric_limits<int>::max());
	int offset = i * step;
	if (remaining < 0) {
	  fmt::print(std::cerr, "ERROR: Failed during distribution of covariate adjusted permutation jobs.\n");
	  std::exit(-1);
	}

	PermuteData data{
		permutations,
		&m[0],
		&odds_[0],
		static_cast<int>(ncases),
		static_cast<int>(odds.n_rows),
		offset,
		i == nthreads - 1 ? remaining : step,
		seed
	};
	threads.emplace_back(&Permute::permute_thread, data);
	remaining -= step;
  }

  for (auto &t : threads) {
	t.join();
  }
}

/**
 * @brief Handler for generating a subset of permutations within a thread.
 * @param data The permutation paramter container.
 */
void Permute::permute_thread(PermuteData data) {
  StochasticLib3 rng(data.seed);

  for (int i = 0; i < data.nperm; i++) {
	rng.MultiFishersNCHyp(&(*data.permutations)[data.offset + i][0], data.m, data.odds, data.ncases, data.ngroups);
  }

}

